# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 27 Jun 2012 18:58:40 +0000
*               @ALL          0
*               @user         8
