<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: cmcdragonkai
 * Date: Tue, 04 Sep 2012 11:59:38 -0700
 */

$conf['title'] = 'Codex @ Polycademy';
$conf['youarehere'] = 1;
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['rss_type'] = 'rss2';

// end auto-generated content
